export const LOCATIONS: string[] = [
  'Bank vault',
  'Police precinct',
  'Courthouse lobby',
  'City hall',
  'Fire station',
  'Post office',
  'Library reading room',
  'Museum gallery',
  'Newsroom',
  'TV studio set',
  'Skyscraper rooftop',
  'Subway platform',
  'Train carriage',
  'Airport gate',
  'Baggage claim',
  'Bus depot',
  'Diner booth',
  'Coffeehouse counter',
  'Farmers’ market',
  'Nightclub dancefloor',
  'Jewelry boutique',
  'Pawn shop',
  'Hardware store',
  'Flower shop',
  'Warehouse aisle',
  'Factory floor',
  'Data center',
  'Tech repair shop',
];
